### ISSUE TITLE
Add explicit methods of specifying environment variables.

### ISSUE THREAD

**Issue by danbradham** [cpenv/cpenv#28]
Currently the environment key section of a module file has the following implied methods of setting environment variables.

```
# Set an environment variable
VARIABLE_A: value

# Prepend values to an environment variable
VARIABLE_B:
  - value_a
  - value_b
```

Having keys for set, prepend, append and remove would make it easier to understand how your environment will be modified.

```
# Set an environment variable
VARIABLE_A:
    - set: value

# Set an environment variable to a new list of values
VARIABLE_A:
    - set: 
        - value_a
        - value_b

# Prepend to an environment variable
VARIABLE_B:
    - prepend:
        - value_a
        - value_b

# Append to an environment variable
VARIABLE_C:
    - append:
        - value_a
        - value_b

# Remove an environment variable
PATH:
    - remove: 
        - C:/Python27
        - C:/Python27/Scripts
```

Adding the explicit keys would also make it easier to create a module whose sole purpose is to override configuration values stored in environment variables. Let's say I have a tool that has an environment variable that expects a list of paths used to lookup assets. Maybe I have a new project that requires me to overwrite that environment variable with a new list of paths. Currently this isn't possible, because the implicit method of setting an environment variable only takes a single value.
